connect:
  twitter:
    key: "bzWqLnz2mB970s8OZ4hP1w"
    secret: "vMLQAzsVH6W821mPpQInifYmKXv2zyrlbgtdfaPZGA"
    label: "Twitter"
    
  linked_in:
    key: "ldY1NBcIYDqhmtFnfrgrHu_Diu1-TmOgVHHggpgv_wlKPhXB0v9BbNE4z09sCx_B"
    secret: "VE_YDYbTKuszoKuOCcgsCYw2h1GogDCWHHVMC3ND7nQk0F8MQf4nswXQ8SVdCOXV"
    
  facebook:
    key: "103963339668040"
    secret: "efafd19e100e348950298b4ec245996e"