connect:
  twitter:
    key: "bzWqLnz2mB970s8OZ4hP1w"
    secret: "vMLQAzsVH6W821mPpQInifYmKXv2zyrlbgtdfaPZGA"
    label: "Twitter"

  facebook:
    key: "632c2359465b9d7dc88a4f26d1f0c35f"
    secret: "d251756d57255e090a14caa1c7ab31c3"
    label: "Facebook"
    
  linked_in:
    key: "ldY1NBcIYDqhmtFnfrgrHu_Diu1-TmOgVHHggpgv_wlKPhXB0v9BbNE4z09sCx_B"
    secret: "VE_YDYbTKuszoKuOCcgsCYw2h1GogDCWHHVMC3ND7nQk0F8MQf4nswXQ8SVdCOXV"
    label: "Linkedin"
